project:
  type: website
  output-dir: "docs"
  resources: 
    - path/to/file.pdf

website:
  title: "Guan Chen"
  navbar:
    right:
      - href: other/Guan Chen.docx
        text: Resume
        target: "_blank"
      - text: Data Visualization
        menu:
        - href: epps6356/Druckrey_Review.qmd
          text: Druckrey Video Review
        - href: epps6356/as1.qmd
          text: Assignment 1
        - href: epps6356/data_visualization_review.qmd
          text: Journalistic vs Academic Data Visualization
        - href: epps6356/the_future_of_data_analysis_review.qmd
          text: Review of The Future of Data Analysis
        - href: epps6356/as2.qmd
          text: Assignment 2
        - href: epps6356/as3.qmd
          text: Assignment 3       
        - href: epps6356/data_pitfalls.qmd
          text: Data Analytics Pitfalls Discussion 
        - href: epps6356/prehackathon.qmd
          text: Prehackathon
        - href: epps6356/Frank_Proposal.pptx
          text: Research Proposal
        - href: epps6356/EMBL_discussion.qmd
          text: EMBL Discussion
        - href: epps6356/the_week_in_charts.qmd
          text: McKinsey's Chart Reviews
        - href: epps6356/mckinsey_chart.qmd
          text: McKinsey's Chart Reviews
        - href: epps6356/pfc9.qmd
          text: Time Series Concepts
        - href: epps6356/as5.qmd
          text: Assignment 5
        - href: epps6356/pfc10.qmd
          text: Interactive Bar Chart Code
        - href: epps6356/as6.qmd
          text: Assignment 6
          
format:
  html:
    theme: cyborg
    css: other/styles.css
    toc: true
    warning: false
    error: false
    message: false
    #echo: false

editor: visual

